spring.application.name=partyhelper
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=yourKey
spring.ai.google.genai.chat.model=gemini-3.5-flash
spring.ai.google.genai.chat.response-mime-type=application/json
